name: Docker Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (patch, minor, major)'
        required: true
        default: 'patch'

jobs:

  release:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PACKAGE_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install NPM packages
      run: yarn install --non-interactive

    - name: Update package verions
      run: |
        git config --local user.email "github-ci@nordeck.net"
        git config --local user.name "Nordeck CI"
        npm version ${{ github.event.inputs.version }} --force -m "Version %s"
        git push --follow-tags

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_TOKEN }}

    - name: Build Docker Image
      run: yarn run docker:build -- --push ghcr.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
